AWSTemplateFormatVersion: "2010-09-09"
Description: This stacks deploys new client id IAM role and attach s3 bucket policy.
Resources: 
  rClientRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: test-ads-cicd
      PermissionsBoundary: !Sub 'arn:aws:iam::${AWS::AccountId}:policy/LZ-IAM-Boundary'  
      MaxSessionDuration: 36000
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated:
                - !Sub arn:aws:iam::${AWS::AccountId}:saml-provider/LillyUserAPIGW
            Action: sts:AssumeRoleWithSAML
            Condition:
              StringEquals:
               "SAML:aud": "https://signin.aws.amazon.com/saml"
      ManagedPolicyArns:
        - arn:aws:iam::578225969089:policy/harish-test-s3
        - arn:aws:iam::578225969089:policy/s3-test-bucket
        - arn:aws:iam::578225969089:policy/aaaaaaaaa
