AWSTemplateFormatVersion: '2010-09-09'
Description: >
  Lilly CI/CD Pipeline v2. This template creates a pipeline with a
  GitHub source stage, CodeBuild Build stage, CloudFormation deployment stage,
  and optionally a CodeBuild Test stage.
Parameters:
  ProjectName:
    Description: The name of the project.
    Type: String
    MaxLength: 42
    AllowedPattern: "[a-zA-Z][A-Za-z0-9-]*"
    ConstraintDescription: must begin with a letter and contain only alphanumeric characters or dashes (-).
  ParameterFileName:
    Description: The name of the template configuration file (must be added to artifacts in buildspec file).
    Type: String
    Default: params.dev.json
  CodeBuildImage:
    Description: The container image CodeBuild uses to run the pre-deploy and post-deploy buildspecs.
    Type: String
    Default: aws/codebuild/standard:4.0
    AllowedValues:
      - aws/codebuild/amazonlinux2-x86_64-standard:3.0
      - aws/codebuild/amazonlinux2-x86_64-standard:2.0
      - aws/codebuild/amazonlinux2-aarch64-standard:1.0
      - aws/codebuild/standard:4.0
      - aws/codebuild/standard:3.0
  BuildspecPath:
    Description: The relative path to the buildspec file.
    Type: String
    Default: buildspec.yml
  CodeBuildComputeType:
    Description: The container size for the pre-deployment CodeBuild project. https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html
    Type: String
    Default: BUILD_GENERAL1_SMALL
    AllowedValues:
      - BUILD_GENERAL1_SMALL  # Use up to 3 GB memory and 2 vCPUs for builds.
      - BUILD_GENERAL1_MEDIUM # Use up to 7 GB memory and 4 vCPUs for builds.
      - BUILD_GENERAL1_LARGE  # Use up to 15 GB memory and 8 vCPUs for builds.
  PostDeployBuildspecPath:
    Description: The relative path to the post-deployment buildspec file. Blank if you don't need a post-deployment build.
    Type: String
    Default: post-deploy-buildspec.yml
  PostDeployCodeBuildComputeType:
    Description: The container size for the post-deployment CodeBuild project. https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-compute-types.html
    Type: String
    Default: BUILD_GENERAL1_SMALL
    AllowedValues:
      - BUILD_GENERAL1_SMALL  # Use up to 3 GB memory and 2 vCPUs for builds.
      - BUILD_GENERAL1_MEDIUM # Use up to 7 GB memory and 4 vCPUs for builds.
      - BUILD_GENERAL1_LARGE  # Use up to 15 GB memory and 8 vCPUs for builds.
  PostBackTestResults:
    Description: Adds a CodeBuild project to post-back buildspec results to GitHub.
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
  TemplatePath:
    Description: The relative path to the CloudFormation template file.
    Type: String
    Default: template.yml
  CreateGitHubRepoFromBlueprint:
    Description: Creates a new GitHub repo and seeds it with one of EDAT's blueprints. 'RepositoryName' must not reference an existing repository.
    Type: String
    Default: "false"
    AllowedValues:
      - "false"
      - "SPA"
      - "SAM"
      - "CFN_ONLY"
      - "FARGATE"
      - "FULL_STACK"
      - "SERVERLESS"
      - "EC2_COTS"
      - "COGNITO"
      - "DYNAMODB"
      - "RDS"
      - "DOCUMENTDB"
      - "EFS"
      - "ELASTICACHE"
      - "ELASTICSEARCH"
      - "FSX"
      - "NEPTUNE"
      - "CASSANDRA"
  RepositoryName:
    Description: GitHub repository name.
    Type: String
  RepositoryBranch:
    Description: GitHub repository branch name (master, main, dev, etc.).
    Type: String
  GitHubOwner:
    Type: String
    Default: EliLillyCo
  GitHubSecret:
    Description: This should be a 32 character random string.
    Type: String
    NoEcho: true
  GitHubPAT:
    Description: GitHub Personal Access Token
    Type: String
    NoEcho: true
  CreateECRRepo:
    Description: Adds an ECR repository that the CodeBuild jobs and CloudFormation can access.
    Type: String
    Default: "false"
    AllowedValues:
      - "true"
      - "false"
  Custodian:
    Description: System ID of the project's custodian.
    Type: String
  PrimaryITContact:
    Description: System ID of the project's primary IT contact.
    Type: String
  SystemOwner:
    Description: System ID of the project's system owner.
    Type: String
  CostCenter:
    Description: Cost center ID.
    Type: String
  CostCenterApprover:
    Description: System ID of the cost center approver.
    Type: String
  Level1BusinessArea:
    Description: Business area of the project.
    Type: String
  DataClassification:
    Description: Data classification of the project.
    Type: String
    AllowedValues:
      - Green
      - Yellow
      - Orange
      - Red
  Environment:
    Description: Environment where the project lives.
    Type: String
    AllowedValues:
      - Dev
      - QA
      - Prod
